name: 'Ionicons Production Release'

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: choice
        description: Which version should be published?
        options:
          - patch
          - minor
          - major
      tag:
        required: true
        type: choice
        description: Which npm tag should this be published to?
        options:
          - latest

jobs:
  release-ionicons:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish to NPM
        uses: ./.github/workflows/actions/publish-npm
        with:
          tag: ${{ inputs.tag }}
          version: ${{ inputs.version }}
          working-directory: './'
          token: ${{ secrets.NPM_TOKEN }}
          createRelease: true
          ghToken: ${{ secrets.GITHUB_TOKEN }}
